server:
  port: 8100

spring:
  application:
    name: orion-account-organisation
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:postgresql://localhost:5432/account-organisations"
    username: local
    password: local
    hikari:
      connection-timeout: 5000
      validation-timeout: 3000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update

#logging:
#  level:
#    root: INFO
#    platform.application: DEBUG