server:
  port: 8101

spring:
  application:
    name: orion-engineering-project
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/engineering_projects}
    username: ${DB_USERNAME:local}
    password: ${DB_PASSWORD:local}
    hikari:
      connection-timeout: 5000
      validation-timeout: 3000
  jpa:
    database: postgresql
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate

#logging:
#  level:
#    root: INFO
#    platform.application: DEBUG